// Copyright (c) 2026 guyuemeng
//
// cxxaux is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan
// PSL v2. You may obtain a copy of Mulan PSL v2 at:
//             http://license.coscl.org.cn/MulanPSL2
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
// KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
//
// See the Mulan PSL v2 for more details.

#ifdef IMPORT_ELF_DETAIL
#undef IMPORT_ELF_DETAIL

namespace detail {

template <typename BitNArch>
struct ElfNSection {
  const std::string_view name;
  const std::string_view content;
  const typename BitNArch::Shdr* hdr;
};

template <typename BitNArch>
struct ElfNProgram {
  const typename BitNArch::Phdr* hdr;
};

template <typename BitNArch>
class ProgramLoader {
  using Ehdr = typename BitNArch::Ehdr;
  using Shdr = typename BitNArch::Shdr;
  using Phdr = typename BitNArch::Phdr;

public:
  ProgramLoader(std::string_view buf)
      : decoder(buf.data(), buf.size()), ehdr(decoder.peek<Ehdr>()) {}

  std::vector<ElfNProgram<BitNArch>> doit() {
    if (ehdr->e_phoff == 0)
      return {};

    const Shdr& initial = getShdrInitializer();
    size_t phSize = ehdr->e_phnum == 0xffff ? initial.sh_info : ehdr->e_phnum;

    std::vector<ElfNProgram<BitNArch>> programs;
    programs.reserve(phSize);
    decoder.seekg(ehdr->e_phoff);
    for (size_t i = 0; i < phSize; ++i) {
      auto* phdr = decoder.get<Phdr>();
      programs.push_back({phdr});
    }
    return programs;
  }

private:
  const Shdr& getShdrInitializer() {
    decoder.seekg(ehdr->e_shoff);
    return *(decoder.peek<Shdr>());
  }

private:
  BinaryDecoder decoder;
  const Ehdr* ehdr;
};

template <typename BitNArch>
class SectionLoader {
  using Ehdr = typename BitNArch::Ehdr;
  using Shdr = typename BitNArch::Shdr;

public:
  explicit SectionLoader(std::string_view buf)
      : decoder(buf.data(), buf.size()), ehdr(decoder.peek<Ehdr>()) {}

  std::vector<ElfNSection<BitNArch>> doit() {
    if (ehdr->e_shoff == 0)
      return {};

    const Shdr& initial = getShdrInitializer();
    size_t shnum = ehdr->e_shnum == 0 ? initial.sh_size : ehdr->e_shnum;

    std::optional<BinaryDecoder> shstr;
    if (ehdr->e_shstrndx != SHN_UNDEF) {
      size_t shstrndx =
          ehdr->e_shstrndx == SHN_XINDEX ? initial.sh_link : ehdr->e_shstrndx;
      decoder.seekg(ehdr->e_shoff + ehdr->e_shentsize * shstrndx);
      auto* str = decoder.peek<Shdr>();
      shstr = getSectionContent(str);
    }

    std::vector<ElfNSection<BitNArch>> sections;
    decoder.seekg(ehdr->e_shoff);
    for (size_t i = 0; i < shnum; ++i) {
      auto* shdr = decoder.get<Shdr>();
      std::string_view shName;
      if (shstr.has_value()) {
        shName = getSectionName(shstr.value(), shdr);
      }
      BinaryDecoder cnt = getSectionContent(shdr);
      sections.push_back({shName, {cnt.data(), cnt.size()}, shdr});
    }

    return sections;
  }

private:
  const Shdr& getShdrInitializer() {
    decoder.seekg(ehdr->e_shoff);
    return *(decoder.peek<Shdr>());
  }

  std::string_view getSectionName(BinaryDecoder shStrTbl,
                                  const Shdr* shdr) const {
    shStrTbl.seekg(shdr->sh_name);
    return shStrTbl.peekc();
  }

  BinaryDecoder getSectionContent(const Shdr* shdr) {
    return decoder.slice(shdr->sh_offset, shdr->sh_size);
  }

private:
  BinaryDecoder decoder;
  const Ehdr* ehdr;
};

inline std::vector<ElfNProgram<Bit32Arch>>
loadElf32Programs(std::string_view buf) {
  return ProgramLoader<Bit32Arch>(buf).doit();
}

inline std::vector<ElfNProgram<Bit64Arch>>
loadElf64Programs(std::string_view buf) {
  return ProgramLoader<Bit64Arch>(buf).doit();
}

inline std::vector<ElfNSection<Bit32Arch>>
loadElf32Sections(std::string_view buf) {
  return SectionLoader<Bit32Arch>(buf).doit();
}

inline std::vector<ElfNSection<Bit64Arch>>
loadElf64Sections(std::string_view buf) {
  return SectionLoader<Bit64Arch>(buf).doit();
}

} // namespace detail

#endif // IMPORT_ELF_DETAIL

#ifdef IMPORT_ELF_IMPL
#undef IMPORT_ELF_IMPL

template <typename BitNArch>
class ElfImpl final : public Elf {
  using Ehdr = typename BitNArch::Ehdr;
  using Phdr = typename BitNArch::Phdr;
  using Shdr = typename BitNArch::Shdr;
  using Sym = typename BitNArch::Sym;

public:
  ElfImpl(BinaryDecoder decoder) {
    ehdr_ = decoder.peek<Ehdr>();
    loadPrograms(decoder);
    loadSections(decoder);
  }

  EIClass archBits() const override {
    return static_cast<EIClass>(ehdr_->e_ident[EI_CLASS]);
  }

  EIData encoding() const override {
    return static_cast<EIData>(ehdr_->e_ident[EI_DATA]);
  }

  EType type() const override { return static_cast<EType>(ehdr_->e_type); }

  EMachine machine() const override {
    return static_cast<EMachine>(ehdr_->e_machine);
  }

  size_t s_size() const override { return sections_.size(); }

  std::unique_ptr<Section> s_at(size_t ndx) const override {
    const auto& s = sections_.at(ndx);
    if (s.hdr->sh_type != static_cast<uint32_t>(SHType::SHT_NOBITS)) {
      return std::make_unique<Section>(
          s.name, static_cast<SHType>(s.hdr->sh_type),
          static_cast<SHFlags>(s.hdr->sh_flags),
          std::make_pair(s.content.data(), s.content.size()));
    }
    return std::make_unique<Section>(s.name,
                                     static_cast<SHType>(s.hdr->sh_type),
                                     static_cast<SHFlags>(s.hdr->sh_flags));
  }

  size_t p_size() const override { return programs_.size(); }

  std::unique_ptr<Program> p_at(size_t ndx) const override {
    const auto* phdr = programs_.at(ndx).hdr;
    return std::make_unique<Program>(
        static_cast<PType>(phdr->p_type), static_cast<PFlags>(phdr->p_flags),
        phdr->p_offset, phdr->p_vaddr, phdr->p_paddr, phdr->p_filesz,
        phdr->p_memsz, phdr->p_align);
  }

  template <typename OStream>
  void dump(OStream& os) const {
    for (const auto& sym : sections_) {
      BinaryDecoder symTab(sym.content.data(), sym.content.size());
      while (symTab.tellg() != BinaryDecoder::eob) {
        auto* st = symTab.get<Sym>();
        if (st->st_info == static_cast<uint8_t>(STType::STT_FUNC)) {
          auto strTab =
              BinaryDecoder(sections_[sym.hdr->sh_link].content.data(),
                            sections_[sym.hdr->sh_link].content.size());
          strTab.seekg(st->st_name);
          os << strTab.getc() << '\n';
        }
      }
    }
  }

private:
  void dumpImpl(void* os) const override {
    auto* stream = static_cast<std::ostream*>(os);
    this->dump(*stream);
  }

  void loadPrograms(BinaryDecoder decoder) {
    if constexpr (std::is_same_v<BitNArch, Bit32Arch>) {
      programs_ = detail::loadElf32Programs({decoder.data(), decoder.size()});
    } else if constexpr (std::is_same_v<BitNArch, Bit64Arch>) {
      programs_ = detail::loadElf64Programs({decoder.data(), decoder.size()});
    }
  }

  void loadSections(BinaryDecoder decoder) {
    if constexpr (std::is_same_v<BitNArch, Bit32Arch>) {
      sections_ = detail::loadElf32Sections({decoder.data(), decoder.size()});
    } else if constexpr (std::is_same_v<BitNArch, Bit64Arch>) {
      sections_ = detail::loadElf64Sections({decoder.data(), decoder.size()});
    }
  }

private:
  const Ehdr* ehdr_;
  std::vector<detail::ElfNProgram<BitNArch>> programs_;
  std::vector<detail::ElfNSection<BitNArch>> sections_;
};

#endif // IMPORT_ELF_IMPL
